title: Tahnee Alexandra
name: Tahnee Alexandra
description: A crisp and melodious Geordie voice, serving chipper authenticity with every read.
audio-reel: /assets/audio/reel.mp3
site-keywords: 'geordie, voiceover, voiceover artist'
big-image: /assets/images/alex-headshot.jpg
small-image: /assets/images/alex-headshot.jpg
email: someone@example.com

# Social links

#facebook_username: DUMMY
twitter_username: alexandratahnee
instagram_username: alex_tahnee_voiceover
#linkedin_username: DUMMY
#youtube_channel_id: UCk_12ABCD-U_ABCD1234ABC
#google-analytics: UA-12345679-1

# Colours
colours:
  orange: "ffb00f"
  black: "000000"
  light-gray: "f8f8f8"
  dark-gray: "282828"

##########################################
# DO NOT CHANGE ANYTHING BELOW THIS LINE
##########################################
markdown: kramdown
url: ''
baseurl: '/ghpages'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/